name: Generate Image Links

on:
  push:
    paths:
      - "images/**"    # Triggera l'azione quando viene caricata o modificata una immagine nella cartella "images"

jobs:
  generate-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Generate image links
        run: |
          python3 generate_js.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add images.js
          git commit -m "Update image links"
          git push

